sample_map: './sample_map.tsv'

dirs:
        input: '/cluster/project/nexus/marcus/singlecell_pipeline_test/zheng_melanoma_typing/analysis/atypical_removed/'
#/cluster/project/nexus/marcus/singlecell_pipeline_test/zheng_melanoma_typing/analysis/atypical_removed/Zheng_sorted_merged.genes_cells_filtered.corrected.atypical_removed.RDS
        output: './'

call:
        cross_validation: 'Rscript /cluster/project/nexus/benchmarking/celltyping/git/scripts/cv_k_fold.R'
        cv_summary: 'Rscript /cluster/project/nexus/benchmarking/celltyping/git/scripts/cv_summary.R'
        
        find_markers: 'Rscript /cluster/project/nexus/benchmarking/celltyping/git/scripts/find_markers.R'
        convert_markers: 'python /cluster/project/nexus/benchmarking/celltyping/git/scripts/convert_markers.py'
        
        rf_train: '/cluster/project/nexus/benchmarking/celltyping/git/scripts/rf_train.R'
        svm_train: '/cluster/project/nexus/benchmarking/celltyping/git/scripts/svm_train.R'
        garnett_train: '/cluster/project/nexus/benchmarking/celltyping/git/scripts/garnett_train.R'

        rf_test: '/cluster/project/nexus/benchmarking/celltyping/git/scripts/rf_test.R'
        svm_test: '/cluster/project/nexus/benchmarking/celltyping/git/scripts/svm_test.R'
        garnett_test: '/cluster/project/nexus/benchmarking/celltyping/git/scripts/garnett_test.R'
        nexus_test: '/cluster/project/nexus/benchmarking/celltyping/git/scripts/nexus_test.R'
        
        statistics: 'statistics.R'
        plot: 'plot_stats.R'
