output_dir: output
datafile: input/data.csv
labfile: input/Labels.csv
column: 1
number_of_features: 0
tools_to_run:
  - sc-pipeline-celltyping
  - Garnett_CV
  - CellAssign
  - SVMRejection
  - RF

# add general marker file path
Garnett_CV:
  markers: <path to Gernett marker gene file>
