input_output:
    sample_map: "/path/to/samplemap"
    input_dir: "/path/to/input/"
    output_dir: "/path/to/output/"
    tmp_dir: "/path/to/tmp/"


resources:
    conda_path: ""
    snakemake_path: ""
    celltype_methods: ["svm","rf","garnett","scROSI"]
    trained_models: ["svm","rf","garnett"],
    celltype_config: "/cluster/project/nexus/benchmarking/celltyping/git/marker_files/PBMC/celltype_config_PBMC.txt"

statistics:

  cross_validation:
    call: "/cluster/project/nexus/benchmarking/celltyping/git/scripts/cv_k_folds.R"
    scratch: "1000"
    mem: "1000"
    time: "200"
    threads: 1
    k_folds: 10
    params: ""

  cv_summary:
    call: "/cluster/project/nexus/benchmarking/celltyping/git/scripts/cv_summary.R"
    scratch: "1000"
    mem: "1000"
    time: "200"
    threads: 1
    params: ""

  calc_accuracy:
    call: ""
    scratch: ""
    mem: ""
    time: ""
    threads: 1
    params: ""

  plot_stats:
    call: ""
    scratch: ""
    mem: ""
    time: ""
    threads: 1
    params: ""

preprocessing:

  sce_to_cds:
    call: "Rscript /cluster/project/nexus/benchmarking/celltyping/git/scripts/convert_sce_to_cds.R"
    scratch: "1000"
    mem: "1000"
    time: "200"
    threads: 1
    params: ""
    conda: "/cluster/project/nexus/benchmarking/celltyping/docs/conda_envs/garnett.yaml"

methods:

  rf:
    test:
      call: "Rscript /cluster/project/nexus/benchmarking/celltyping/git/scripts/RF_test.R"
      scratch: "1000"
      mem: "1000"
      time: "200"
      threads: 1

  svm:
    test:
      call: "Rscript /cluster/project/nexus/benchmarking/celltyping/git/scripts/SVM_test.R"
      scratch: "1000"
      mem: "1000"
      time: "200"
      threads: 1
  
  fcnn:
    test:
      call: "Rscript /cluster/project/nexus/benchmarking/celltyping/git/scripts/fcNN_test.R"
      scratch: "1000"
      mem: "1000"
      time: "200"
      threads: 1

  garnett:
    test:
      call: "Rscript /cluster/project/nexus/benchmarking/celltyping/git/scripts/test_garnett.R"
      scratch: "1000"
      mem: "1000"
      time: "200"
      threads: 1
      params: ""
    conda: "/cluster/project/nexus/benchmarking/celltyping/docs/conda_envs/garnett.yaml"

  scROSI:
      call: "Rscript /cluster/project/nexus/benchmarking/celltyping/git/scripts/scROSI.R"
      scratch: "2000"
      mem: "4000"
      time: "200"
      threads: 4
