input_output:
    sample_map: "/path/to/samplemap"
    input_dir: "/path/to/input/"
    output_dir: "/path/to/output/"
    tmp_dir: "/path/to/tmp/"

resources:
    conda_path: ""
    celltype_methods: ["svm","rf","garnett","scROSHI"]
    trained_models: ["svm","rf","garnett","scROSHI"],
    celltype_config_gt: "PATH_TO_GIT/marker_files/PBMC/celltype_config_PBMC_groundtruth.txt"

statistics:

  calc_accuracy:
    call: ""
    scratch: ""
    mem: ""
    time: ""
    threads: 1
    params: ""

  plot_stats:
    call: ""
    scratch: ""
    mem: ""
    time: ""
    threads: 1
    params: ""

preprocessing:

  sce_to_cds:
    call: "Rscript PATH_TO_GIT/scripts/convert_sce_to_cds.R"
    scratch: "1000"
    mem: "1000"
    time: "200"
    threads: 1
    params: ""
    conda: "PATH_TO_GIT/docs/conda_envs/garnett.yaml"

methods:

  rf:
    test:
      call: "Rscript PATH_TO_GIT/scripts/RF_test.R"
      scratch: "1000"
      mem: "1000"
      time: "200"
      threads: 1

  svm:
    test:
      call: "Rscript PATH_TO_GIT/scripts/SVM_test.R"
      scratch: "1000"
      mem: "1000"
      time: "200"
      threads: 1

  fcnn:
    test:
      call: "Rscript PATH_TO_GIT/scripts/fcNN_test.R"
      scratch: "1000"
      mem: "1000"
      time: "200"
      threads: 1

  garnett:
    test:
      call: "Rscript PATH_TO_GIT/scripts/test_garnett.R"
      scratch: "1000"
      mem: "1000"
      time: "200"
      threads: 1
      params: ""
    conda: "PATH_TO_GIT/docs/conda_envs/garnett.yaml"

  prep_scROSHI_config:
      call: "Rscript PATH_TO_GIT/scripts/prepare_scROSHI_config.py"
      scratch: "2000"
      mem: "2000"
      time: "200"
      threads: 1

  scROSHI:
      call: "Rscript PATH_TO_GIT/scripts/scROSHI.R"
      scratch: "2000"
      mem: "4000"
      time: "200"
      threads: 4
