input_output:
    sample_map: "/path/to/samplemap"
    input_dir: "/path/to/input/"
    output_dir: "/path/to/output/"
    tmp_dir: "/path/to/tmp/"


resources:
    conda_path: ""
    snakemake_path: ""
    tools: ["svm","rf","garnett"]


statistics:

  cross_validation:
    call: "/cluster/project/nexus/benchmarking/celltyping/git/scripts/cv_k_folds.R"
    scratch: "1000"
    mem: "1000"
    time: "200"
    threads: 1
    k_folds: 10
    params: ""

  cv_summary:
    call: "/cluster/project/nexus/benchmarking/celltyping/git/scripts/cv_summary.R"
    scratch: "1000"
    mem: "1000"
    time: "200"
    threads: 1
    params: ""

  calc_accuracy:
    call: ""
    scratch: ""
    mem: ""
    time: ""
    threads: 1
    params: ""

  plot_stats:
    call: ""
    scratch: ""
    mem: ""
    time: ""
    threads: 1
    params: ""


markers:

  find_markers:
    call: "Rscript /cluster/project/nexus/benchmarking/celltyping/git/scripts/MarkerGeneList.R"
    scratch: "1000"
    mem: "1000"
    time: "200"
    threads: 1
    params: ""

  convert_markers:
    call: "python /cluster/project/nexus/benchmarking/celltyping/git/scripts/convert_marker_file.py"
    scratch: "1000"
    mem: "1000"
    time: "200"
    threads: 1
    params: ""


methods:

  rf:
    train:
      call: "Rscript /cluster/project/nexus/benchmarking/celltyping/git/scripts/train_rf.R"
      scratch: "1000"
      mem: "1000"
      time: "200"
      threads: 1
      params: ""
    test:
      call: "Rscript /cluster/project/nexus/benchmarking/celltyping/git/scripts/test_rf.R"
      scratch: "1000"
      mem: "1000"
      time: "200"
      threads: 1
      params: ""

  svm:
    train:
      call: "Rscript /cluster/project/nexus/benchmarking/celltyping/git/scripts/train_svm.R"
      scratch: "1000"
      mem: "1000"
      time: "200"
      threads: 1
      params: ""
    test:
      call: "Rscript /cluster/project/nexus/benchmarking/celltyping/git/scripts/test_svm.R"
      scratch: "1000"
      mem: "1000"
      time: "200"
      threads: 1
      params: ""

  garnett:
    train: 
      call: "Rscript /cluster/project/nexus/benchmarking/celltyping/git/scripts/train_garnett.R"
      scratch: "1000"
      mem: "1000"
      time: "200"
      threads: 1
      params: ""
    test:
      call: "Rscript /cluster/project/nexus/benchmarking/celltyping/git/scripts/test_garnett.R"
      scratch: "1000"
      mem: "1000"
      time: "200"
      threads: 1
      params: ""
    conda: "/cluster/project/nexus/benchmarking/celltyping/docs/conda_envs/garnett.yaml"

  nexus:
    test:
      call: "Rscript /cluster/project/nexus/benchmarking/celltyping/git/scripts/test_nexus.R"
      scratch: "1000"
      mem: "1000"
      time: "200"
      threads: 1
      params: ""
