---
title: "Result Summary"
author: "Lars Bosshard"
date: "20 11 2020"
output: 
  word_document: 
    fig_caption: yes
    reference_docx: mystyles.docx
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, error=F, message=F, warning=F, cache=F, results='hide', fig.show = 'hide', dpi = 300)
```

```{r}
#library
library(tidyverse)
library(caret)
library(SingleCellExperiment)
library(knitr)
library(cowplot)
library(captioner)
library(Rfast)
library(uwot)
```

```{r}
#Data Path
#############
#training data
train_name = "Adult_PBMC_subset"
mgl_path <- "/Users/bolars/Documents/celltyping/output/mgl_Adult_PBMC_subset"

#testing data
test_name = "Newborn_PBMC_subset"
sce = paste("/Users/bolars/Documents/celltyping/output/",test_name,"_test.RDS",sep="")
pred_path = paste("/Users/bolars/Documents/celltyping/test_run/test_13_10_2020/predicted_lab/",train_name,"/",sep="")
method_name = c("rf","svm","garnett","scROSI")
```

```{r}
#Parameters and functions
'%&%' = function(a,b) paste(a,b,sep="")
tab_nums = captioner(prefix = "Table")
fig_nums = captioner(prefix = "Figure")
fcite = function(x,...) fig_nums(x, display="cite", ...)
tcite = function(x,...) tab_nums(x, display="cite", ...)
theme_set(theme_bw(base_size=10))

f.lab <- function(dat_lab,lab){
  #major labels
  lab <- unique(lab)
  notMaj <- which(!(dat_lab %in% lab[,1]))
  loop1 <- unique(dat_lab[notMaj])
  loop1 <- loop1[!(loop1 %in% c("Unknown","Uncertain"))]
  res_mat <- data.frame(maj=dat_lab,sub=dat_lab)
  for(i in loop1){
    res_mat[res_mat[,1] == i,1] <- lab[lab[,2]==i,1]
  }
  #sub labels
  notSub <- which(!(dat_lab %in% lab[,2]))
  loop2 <- unique(dat_lab[notSub])
  loop2 <- loop2[!(loop2 %in% c("Unknown","Uncertain"))]
  for(j in loop2){
    res_mat[res_mat[,2] == j,2] <- "Unknown"
  }
  return(res_mat)
}
```

```{r}
#load input data
files_list <- list.files(pred_path,pattern = "predicted_labels")
sce_data = readRDS(sce)
lab_maj <- sce_data@metadata$ground_truth_major
lab_sub <- sce_data@metadata$ground_truth_minor
lab_sub[lab_sub=="none"] <- lab_maj[lab_sub=="none"]
barcode = colnames(sce_data)
```

```{r}
ll <- files_list[grep(test_name,files_list)]
#lab_mat: matrix with predicted and true labels
lab_mat <- as.data.frame(matrix(NA,
                                nrow = length(lab_sub),
                                ncol = length(method_name)+2))
lab_mat[,1:2] <- cbind(lab_maj,lab_sub)
colnames(lab_mat)[1:2] <- c("lab_maj","lab_sub")
for(i in 1:length(method_name)){
  t.method <- method_name[i]
  t.name <- ll[grep(t.method,ll)]
  t.dat <- read_csv(pred_path %&% t.name)
  lab_mat[,i+2] <- t.dat[,"celltype_final"]
  colnames(lab_mat)[i+2] <- t.method
}
lab_mat <- as.data.frame(apply(lab_mat,2,str_to_title))
```

# Training Data: `r train_name`
# Test Data: `r test_name`

### Ground truth: `r test_name`

```{r}
fig_nums("true", caption = "True major- and sublabels")
```

```{r true, fig.show="asis", fig.width=8, fig.height=5, fig.cap=fig_nums("true")}
#plot true major- subtypes
p1 <- lab_mat %>%
  group_by(lab_sub)%>%
  summarise(count = n())%>%
  ggplot(aes(x=lab_sub,y=count))+
  geom_col()+
  theme_bw()+
  ggtitle("Subtypes")+
  theme(axis.text=element_text(size=8), axis.text.x = element_text(angle=45, hjust=1, vjust=1),axis.title.x=element_blank())

p2 <- lab_mat %>%
  group_by(lab_maj)%>%
  summarise(count = n())%>%
  ggplot(aes(x=lab_maj,y=count))+
  geom_col()+
  theme_bw()+
  ggtitle("Major types")+
  theme(axis.text=element_text(size=8), axis.text.x = element_text(angle=45, hjust=1, vjust=1),axis.title.x=element_blank())

plot_grid(p1,p2, nrow = 1,rel_widths = c(1.5,1))
```

### UMAP plot ground truth

```{r}
fig_nums("umap", caption = "UMAP of true sublabels")
```

```{r umap, fig.show="asis", fig.width=6, fig.height=4, fig.cap=fig_nums("umap")}
geneList <- read_csv(mgl_path)
geneList <- unique(geneList$gene)
dat <- as.data.frame(t(normcounts(sce_data)))
rownames(dat) <- colnames(sce_data)
colnames(dat) <- gsub("-","_",colnames(dat))
dat_filter <- dat[,colnames(dat) %in% geneList]
# UMAP
set.seed(123) #for reproducible umap plots
fit_umap <- umap(dat_filter)
# plot
tibble(umap1=fit_umap[,1],
       umap2=fit_umap[,2],
       cluster=as.factor(lab_sub))%>%
  ggplot(aes(x=umap1,y=umap2,col=cluster))+
  geom_point()+
  scale_colour_brewer(name="", palette="Paired", direction = 1) +
  theme_bw()
```

## Prediction of: `r method_name` 

```{r}
######################################
sub_lev <- c(unique(lab_mat$lab_sub),"Unknown")
sub_lev2 <- unique(lab_mat$lab_sub)
maj_lev <- unique(lab_mat$lab_maj)
sub_lev3 <- c(unique(lab_mat$lab_sub),"Unknown","Uncertain")
maj_lev2 <- c(unique(lab_mat$lab_maj),"Unknown","Uncertain")
com_lev <- c(unique(c(lab_mat$lab_sub,lab_mat$lab_maj)),"Unknown","Uncertain")
accuracy_M <- matrix(NA,nrow = length(maj_lev),ncol = 0)
accuracy_S <- matrix(NA,nrow = length(sub_lev2),ncol = 0)
F1_M <- matrix(NA,nrow = length(maj_lev),ncol = 0)
F1_S <- matrix(NA,nrow = length(sub_lev2),ncol = 0)
overall_M <- matrix(NA,nrow = 8,ncol = 0)
overall_S <- matrix(NA,nrow = 8,ncol = 0)
conf_mat_S <- list()
conf_mat_M <- list()
nn <- character()
```

```{r}
for (i in 1:(ncol(lab_mat)-2))
lab_mat[!(lab_mat[,i+2] %in% com_lev),i+2] <- "Unknown"
```

```{r}
#confusion matrix: accuracy, F1, overall statistics
for (i in 1:length(method_name)){
  j <- method_name[i]
  if (all(lab_mat[,j] %in% sub_lev)){
    t.dat <- lab_mat[,c("lab_sub",j)]
    t.dat <- subset(t.dat,t.dat[,j]!="Unknown")
    unkn <- (length(lab_mat[,j])-nrow(t.dat))/length(lab_mat[,j])
    pred <- factor(t.dat[,j],levels = sub_lev2)
    gt <- factor(t.dat[,"lab_sub"],levels = sub_lev2)
    t.tmp <- confusionMatrix(pred,gt)
    accuracy_S <- cbind(accuracy_S,round(t.tmp$byClass[,"Balanced Accuracy"],4))
    F1_S <- cbind(F1_S,round(t.tmp$byClass[,"F1"],4))
    over <- c(round(t.tmp$overall,4),unkn)
    names(over) <- c(names(t.tmp$overall),"Unknown")
    overall_S <- cbind(overall_S,over)
    #confusion matrix with Unknown, Uncertain
    pred <- factor(lab_mat[,j],levels = sub_lev)
    gt <- factor(lab_mat[,"lab_sub"],levels = sub_lev)
    t.tmp <- confusionMatrix(pred,gt)
    conf_mat_S[[j]] <- t.tmp$table
  }
  else if (all(lab_mat[,j] %in% com_lev)){
    res <- f.lab(lab_mat[,j],lab_mat[,1:2])
    ######
    #major
    ######
    res <- add_column(res,{{j}} :=lab_mat[,1])
    t.dat <- res %>%
      filter(maj != "Unknown", maj != "Uncertain")
    unkn <- (nrow(res)-nrow(t.dat))/nrow(res)
    pred <- factor(t.dat[,1],levels = maj_lev)
    gt <- factor(t.dat[,j],levels = maj_lev)
    t.tmp <- confusionMatrix(pred,gt)
    accuracy_M <- cbind(accuracy_M,round(t.tmp$byClass[,"Balanced Accuracy"],4))
    F1_M <- cbind(F1_M,round(t.tmp$byClass[,"F1"],4))
    over <- c(round(t.tmp$overall,4),unkn)
    names(over) <- c(names(t.tmp$overall),"Unknown")
    overall_M <- cbind(overall_M,over)
    #confusion matrix with Unknown, Uncertain
    pred <- factor(res[,1],levels = maj_lev2)
    gt <- factor(res[,j],levels = maj_lev2)
    t.tmp <- confusionMatrix(pred,gt)
    conf_mat_M[[j]] <- t.tmp$table
    ####
    #sub
    ####
    res <- f.lab(lab_mat[,j],lab_mat[,1:2])
    res <- add_column(res,{{j}} :=lab_mat[,2])
    t.dat <- res %>%
      filter(sub != "Unknown", sub != "Uncertain")
    unkn <- (nrow(res)-nrow(t.dat))/nrow(res)
    pred <- factor(t.dat[,2],levels = sub_lev2)
    gt <- factor(t.dat[,j],levels = sub_lev2)
    t.tmp <- confusionMatrix(pred,gt)
    accuracy_S <- cbind(accuracy_S,round(t.tmp$byClass[,"Balanced Accuracy"],4))
    F1_S <- cbind(F1_S,round(t.tmp$byClass[,"F1"],4))
    over <- c(round(t.tmp$overall,4),unkn)
    names(over) <- c(names(t.tmp$overall),"Unknown")
    overall_S <- cbind(overall_S,over)
    nn <- c(nn,j)
    #confusion matrix with Unknown, Uncertain
    pred <- factor(res[,2],levels = com_lev)
    gt <- factor(res[,j],levels = com_lev)
    t.tmp <- confusionMatrix(pred,gt)
    conf_mat_S[[j]] <- t.tmp$table
    }
}
#######################################
colnames(accuracy_S) <- method_name
colnames(accuracy_M) <- nn
colnames(F1_S) <- method_name
colnames(F1_M) <- nn
colnames(overall_S) <- method_name
colnames(overall_M) <- nn
```

### Overall accuracy

```{r}
fig_nums("acc", caption = "Accuracy of the methods for subtypes and major types")
```

```{r acc, fig.show="asis", fig.width=5, fig.height=4, fig.cap=fig_nums("acc")}
name1 <- colnames(overall_S)[1:(ncol(overall_S)-ncol(overall_M))]
name2 <- paste(colnames(overall_M),"_sub",sep="")
name3 <- paste(colnames(overall_M),"_maj",sep="")

d.acc <- as_tibble(t(overall_S)) %>%
  add_row(as_tibble(t(overall_M))) %>%
  add_column(method=c(name1,name2,name3))

d.acc %>%
  ggplot(aes(x=method,y=Accuracy)) +
  geom_errorbar(aes(ymin=AccuracyLower,ymax=AccuracyUpper),width=0.2)+
  geom_point()+
  theme(axis.text=element_text(size=8), axis.text.x = element_text(angle=45, hjust=1, vjust=1))
```

```{r}
fig_nums("mis", caption = "Proportionof Unknown labels for the methods")
```

### Proportion of Unknown labels

```{r mis, fig.show="asis", fig.width=4, fig.height=3, fig.cap=fig_nums("mis")}
d.acc %>%
  ggplot(aes(x=method,y=Unknown))+
  geom_col()+
  theme(axis.text=element_text(size=8), axis.text.x = element_text(angle=45, hjust=1, vjust=1))
```

## F1 statistics on cell level

### Methods

```{r}
fig_nums("cell_s", caption = "F1 for the methods")
```

```{r cell_s, fig.show="asis", fig.width=6, fig.height=3, fig.cap=fig_nums("cell_s")}
type <- str_split(rownames(F1_S),": ",simplify = T)[,2]
tmp <- F1_S
rownames(tmp) <- type
d.cell <- tibble(as.data.frame(tmp)) %>%
  add_column(cell = rownames(tmp)) %>%
  gather("rf","svm","garnett","scROSI",key = "method",value = "F1")

d.cell %>%
  ggplot(aes(x=method,y=F1,fill=cell))+
  geom_bar(stat="identity", color="black", position="dodge")+
  scale_fill_brewer(name="", palette="Spectral", direction = 1) +
  ggtitle("Subtypes")+
  theme_bw()
```

```{r}
fig_nums("cell_m", caption = "F1 for the methods")
```

```{r cell_m, fig.show="asis", fig.width=4, fig.height=3, fig.cap=fig_nums("cell_m")}
type <- str_split(rownames(F1_M),": ",simplify = T)[,2]
tmp <- F1_M
rownames(tmp) <- type
d.cell <- tibble(as.data.frame(tmp)) %>%
  add_column(cell = rownames(tmp)) %>%
  gather("garnett","scROSI",key = "method",value = "F1")

d.cell %>%
  ggplot(aes(x=method,y=F1,fill=cell))+
  geom_bar(stat="identity", color="black", position="dodge")+
  scale_fill_brewer(name="", palette="Spectral", direction = 1) +
  ggtitle("Major types")+
  theme_bw()
```

### Cell types

```{r}
fig_nums("cell_s2", caption = "F1 on cell level")
```

```{r cell_s2, fig.show="asis", fig.width=6, fig.height=3, fig.cap=fig_nums("cell_s2")}
type <- str_split(rownames(F1_S),": ",simplify = T)[,2]
tmp <- F1_S
rownames(tmp) <- type
d.cell <- tibble(as.data.frame(tmp)) %>%
  add_column(cell = rownames(tmp)) %>%
  gather("rf","svm","garnett","scROSI",key = "method",value = "F1")

d.cell %>%
  ggplot(aes(x=cell,y=F1,fill=method))+
  geom_bar(stat="identity", color="black", position="dodge")+
  scale_fill_brewer(name="", palette="Spectral", direction = 1) +
  ggtitle("Subtypes")+
  theme_bw()+
  theme(axis.text=element_text(size=8), axis.text.x = element_text(angle=45, hjust=1, vjust=1))
```

```{r}
fig_nums("cell_m2", caption = "F1 on cell level")
```

```{r cell_m2, fig.show="asis", fig.width=4, fig.height=3, fig.cap=fig_nums("cell_m2")}
type <- str_split(rownames(F1_M),": ",simplify = T)[,2]
tmp <- F1_M
rownames(tmp) <- type
d.cell <- tibble(as.data.frame(tmp)) %>%
  add_column(cell = rownames(tmp)) %>%
  gather("garnett","scROSI",key = "method",value = "F1")

d.cell %>%
  ggplot(aes(x=cell,y=F1,fill=method))+
  geom_bar(stat="identity", color="black", position="dodge")+
  scale_fill_brewer(name="", palette="Spectral", direction = 1) +
  ggtitle("Major types")+
  theme_bw()+
  theme(axis.text=element_text(size=8), axis.text.x = element_text(angle=45, hjust=1, vjust=1))
```


### Confusion Matrix

```{r,results="asis"}
for (i in 1:length(method_name)){
  nn <- method_name[i]
  tab <- conf_mat_S[[i]]
  print(kable(tab[which(rownames(tab) %in% sub_lev3),
                  which(colnames(tab) %in% sub_lev2)],
              caption = paste(nn,"_subtypes",sep="")))
}
for (j in 1:length(colnames(F1_M))){
  nn <- colnames(F1_M)[j]
  tab <- conf_mat_M[[j]]
  print(kable(tab[,which(colnames(tab) %in% maj_lev)],
              caption = paste(nn,"_majortypes",sep="")))
}

```

